---
title: "Make figures"
output: html_notebook
---

# Results

```{r, message=F, warning=F}
require(ggplot2)
require(tidyr)
require(dplyr)
require(reshape2)
  
results_dir <- '../graph_conv_net/experiments/results'
figures_dir <- '../thesis/figures'
getwd()
```

## functions

```{r}
process_single_lc <- function(df) {
  processed <- df %>% 
    melt(id.vars=c('epoch'), value.name='MAE') %>% 
    mutate(variable = sub('_mae', '', variable),
           variable = replace(variable, variable == 'valid', 'validation'),
           variable = replace(variable, variable == 'train', 'training'),
           variable = factor(variable, levels=c('validation', 'training'))) %>% 
    mutate(epoch = as.integer(epoch)) %>% 
    mutate(MAE = as.double(MAE))
return(processed)
}

process_multiple_lc <- function(df, target_column) {
  processed <- df %>% 
    melt(id.vars=c(target_column, 'epoch'), value.name='MAE') %>% 
    mutate(variable = sub('_mae', '', variable),
           variable = replace(variable, variable == 'valid', 'validation'),
           variable = replace(variable, variable == 'train', 'training'),
           variable = factor(variable, levels=c('validation', 'training'))) %>% 
    mutate(target_column = replace(target_column, target_column == 'None', '0'),  # for target param = neighborhood expansion
           target_column = as.factor(target_column))
  return(processed)
}
```
    


## optimization experiments

```{r}
# experiment_name <- 'old-data-complete'
# 
# df <- read.csv(file.path(results_dir, paste0(experiment_name, '.csv')), stringsAsFactors=F)
# 
# df_long <- df %>%
#   process_single_lc() %>% 
#   na.omit()
# 
# 
# p <- ggplot(data=df_long, aes(x=epoch, y=MAE, linetype=variable)) +
#   geom_line() +
#   scale_y_continuous(limits=c(0, 0.3)) +
#   theme_bw() +
#   theme(plot.title = element_text(hjust = 0.5, size=16)) +
#   labs(title='Training with learning rate scheduling',
#        y='MAE',
#        linetype=element_blank())
# p
```

```{r}
# p <- ggplot(data=df, aes(x=epoch, y=lr)) +
#   geom_line() +
#   theme_bw() +
#   theme(plot.title = element_text(hjust = 0.5, size=16)) +
#   labs(title='Learning rate schedule: reduction on plateau',
#        y='learning rate',
#        linetype=element_blank())
# p
```

## data experiments

method validation experiment:
```{r}
df <- read.csv(file.path(results_dir, 'old-vs-new-data.csv')) %>%
    select(-c(minutes, 'minutes.', lr))  %>% 
    process_multiple_lc(target_column='experiment_name')

ggplot(data=df, aes(x=epoch, y=MAE, color=experiment_name, linetype=variable)) +
  geom_line() + 
  scale_y_continuous(limits=c(0, 0.2)) 
```
```{r}
# add competiton-ds with random split
df <- read.csv(file.path(results_dir, 'competition-vs-full-ds.csv')) %>%
    select(-c(minutes, 'minutes.', lr)) %>% 
    process_multiple_lc(target_column='experiment_name') %>% 
    mutate(
      experiment_name = as.character(experiment_name),
      experiment_name = replace(experiment_name, experiment_name=='exponential-decay-test', 'competition-ds-competion-split'),
      experiment_name = replace(experiment_name, experiment_name=='full-ds', 'full-ds-random-split'),
      experiment_name = as.factor(experiment_name)
      )

ggplot(data=df, aes(x=epoch, y=MAE, color=experiment_name, linetype=variable)) +
  geom_line() + 
  scale_y_continuous(limits=c(0, 0.3)) 
```



## Neighborhood expansion

```{r, message=F}
experiment_name <- 'tencent-mpnn-neighborhood-expansion'  # old run with implicit Hs

df <- read.csv(file.path(results_dir, paste0(experiment_name, '.csv')), stringsAsFactors=F) %>%
  process_multiple_lc(target_column='target_param')


p <- ggplot(data=df, aes(x=epoch, y=MAE, color=target_param, linetype=variable)) +
  geom_line() +
  scale_y_continuous(limits=c(0, 0.4)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size=16)) +
  labs(title='Neighborhood expansion',
       y='MAE',
       color='neighborhood radius',
       linetype=element_blank())
p
# ggsave(file.path(figures_dir, paste0(experiment_name, '.pdf')), p)
```

