---
title: 'create results figures'
output: html_notebook
---


# Functions and settings

```{r, message=F, warning=F}
require(ggplot2)
require(tidyr)
require(dplyr)
require(reshape2)

results_dir <- '../graph_conv_net/experiments/results'
figures_dir <- '../thesis/figures'
getwd()
```


```{r}
process_single_lc <- function(df) {
  processed <- df %>% 
    melt(id.vars=c('epoch'), value.name='MAE') %>% 
    mutate(variable = sub('_mae', '', variable),
           variable = replace(variable, variable == 'valid', 'validation'),
           variable = replace(variable, variable == 'train', 'training'),
           variable = factor(variable, levels=c('validation', 'training'))) %>% 
    mutate(epoch = as.integer(epoch)) %>% 
    mutate(MAE = as.double(MAE))
  return(processed)
}
```


# neighborhood expansion experiments

```{r}
process_multiple_lc <- function(df, target_column) {
  processed <- df %>% 
    select(-c(minutes, lr)) %>% 
    melt(id.vars=c(target_column, 'epoch'), value.name='MAE') %>% 
    mutate(variable = sub('_mae', '', variable),
           variable = replace(variable, variable == 'valid', 'validation'),
           variable = replace(variable, variable == 'train', 'training'),
           variable = factor(variable, levels=c('validation', 'training'))) 
    # mutate(target_column = replace(target_column, target_column == 'None', '0'),  # for target param = neighborhood expansion
    #        target_column = as.factor(target_column))
  processed[, target_column] <- factor(processed[, target_column], levels=c('None', 2, 3, 4, 5, 'inf'))
  return(processed)
}
```


## regular: without root weight



```{r, eval=F}

experiment_name <- 'lc-NE-real-fix'

df <- read.csv(file.path(results_dir, paste0(experiment_name, '.csv')), stringsAsFactors=F) %>%
  process_multiple_lc(target_column='target_param')


p <- ggplot(data=df, aes(x=epoch, y=MAE, color=target_param, linetype=variable)) +
  geom_line() +
  scale_y_continuous(limits=c(0, 0.4)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size=16)) +
  labs(title='Neighborhood expansion',
       y='MAE',
       color='neighborhood radius',
       linetype=element_blank())
p
# ggsave(file.path(figures_dir, paste0('neighborhood-expansion.pdf')), p)
```


## with root weight

```{r}
experiment_name <- 'lc-NE-real-fix-root-weight'

df <- read.csv(file.path(results_dir, paste0(experiment_name, '.csv')), stringsAsFactors=F) %>%
  process_multiple_lc(target_column='target_param')

p <- ggplot(data=df, aes(x=epoch, y=MAE, color=target_param, linetype=variable)) +
  geom_line() +
  scale_y_continuous(limits=c(0, 0.4)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size=16)) +
  labs(title='Neighborhood expansion',
       y='MAE',
       color='neighborhood radius',
       linetype=element_blank())
p
# ggsave(file.path(figures_dir, paste0('neighborhood-expansion-root-weight.pdf')), p)
```


# No weight sharing

```{r}
df_decoupled <- read.csv(file.path(results_dir, 'lc-decoupled-weights.csv')) %>%
  select(-c(minutes, 'minutes.', lr, target_param)) %>%
  filter(epoch < 150) %>% 
  process_single_lc() %>% 
  mutate(experiment_name = 'independent')

df_shared <- read.csv(file.path(results_dir, 'lc-NE-real-fix.csv')) %>%   # todo: swap with better reference (also used below)
  filter(target_param == 'inf') %>% 
  select(-c(minutes, lr, target_param)) %>%
  process_single_lc() %>% 
  mutate(experiment_name = 'shared')

df_comb <- rbind(df_decoupled, df_shared)
write.csv(df_comb, file.path(results_dir, 'lc-decoupled-weights-augmented.csv'))


p <- ggplot(data=df_comb, aes(x=epoch, y=MAE, linetype=variable, color=experiment_name)) +
  geom_line() + 
  theme_bw() + 
  scale_y_continuous(limits=c(0, 0.2)) +
  theme(plot.title = element_text(hjust = 0.5, size=16)) +
  labs(title='Weight sharing between message passing steps',
       color='weights',
       linetype=element_blank())

p

# ggsave(file.path(figures_dir, 'weight-sharing.pdf'), p)
```

# Raw Data: only atom type and bond type


```{r}
df_raw <- read.csv(file.path(results_dir, 'lc-raw-data-processor.csv')) %>%
  select(-c(minutes, lr, target_param)) %>%
  process_single_lc() %>% 
  mutate(experiment_name = 'raw')

df_tencent <- df_shared %>% 
  mutate(experiment_name = 'augmented with features')

df_comb <- rbind(df_raw, df_tencent)
write.csv(df_comb, file.path(results_dir, 'lc-raw-data-processor-augmented.csv'))

p <- ggplot(data=df_comb, aes(x=epoch, y=MAE, linetype=variable, color=experiment_name)) +
  geom_line() + 
  theme_bw() + 
  scale_y_continuous(limits=c(0, 0.2)) +
  theme(plot.title = element_text(hjust = 0.5, size=16)) +
  labs(title='Raw data vs. feature engineering',
       color='input data',
       linetype=element_blank())

# the difference is probably due to the new optimization scheme used in the raw data experiment: only lr-decay of 0.995
# => use NE-real-fix as reference instead

# ggsave(file.path(figures_dir, 'raw-data.pdf'), p, width = 20, height = 13, units = "cm")
p
```



# Implicit Hydrogens

```{r}
df_implicit_h <- read.csv(file.path(results_dir, 'lc-implicit-hydrogens.csv')) %>%
  select(-c(minutes, lr, target_param)) %>%
  process_single_lc() %>% 
  mutate(experiment_name = 'implicit')

df_explicit_h <- df_shared %>% 
  mutate(experiment_name = 'explict')

df_comb <- rbind(df_implicit_h, df_explicit_h)
write.csv(df_comb, file.path(results_dir, 'lc-implicit-hydrogens-augmented.csv'))

p <- ggplot(data=df_comb, aes(x=epoch, y=MAE, linetype=variable, color=experiment_name)) +
  geom_line() + 
  theme_bw() + 
  scale_y_continuous(limits=c(0, 0.2)) +
  theme(plot.title = element_text(hjust = 0.5, size=16)) +
  labs(title='Implicit vs. explicit hydrogen atoms',
       color='hydrogen representation',
       linetype=element_blank())

# ggsave(file.path(figures_dir, 'implict-hydrogens.pdf'), p, width = 20, height = 13, units = "cm")
p
```


## relative direction vectors as additional edge features
```{r}
df_comb %>% filter(epoch == 149)
```

```{r}

df_implicit_h <- read.csv(file.path(results_dir, 'lc-edge-direction-vectors.csv')) %>%
  select(-c(minutes, lr, target_param)) %>%
  process_single_lc() %>% 
  mutate(experiment_name = 'with direction vectors')

df_explicit_h <- df_shared %>% 
  mutate(experiment_name = 'only distance')

df_comb <- rbind(df_implicit_h, df_explicit_h)
write.csv(df_comb, file.path(results_dir, 'lc-edge-direction-vectors-augmented.csv'))

p <- ggplot(data=df_comb, aes(x=epoch, y=MAE, linetype=variable, color=experiment_name)) +
  geom_line() + 
  theme_bw() + 
  scale_y_continuous(limits=c(0, 0.2)) +
  theme(plot.title = element_text(hjust = 0.5, size=16)) +
  labs(title='Direction vectors as additional edge features',
       color='edge features')

# ggsave(file.path(figures_dir, 'edge-direction-vectors.pdf'), p, width = 20, height = 13, units = "cm")
p
```


# best optimization

```{r}
mlruns_dir <- '/home/raph/Desktop/masters_project/graph_conv_net/experiments/mlruns/35'
run_dirs <- list.dirs(mlruns_dir, recursive=F)
df_best_optim <- data.frame()

for (i in 1:4){
  run_df <- read.csv(file.path(run_dirs[i], 'artifacts/learning_curve.csv')) %>% 
    select(-c(minutes)) %>% 
    mutate(run = i) %>% 
    mutate(run = as.factor(run)) %>% 
    mutate(epoch = as.integer(epoch)) %>% 
    mutate(MAE = as.double(valid_mae))
  df_best_optim <- rbind(df_best_optim, run_df)
}
```

```{r}
df_best_optim
```

```{r}
p <- ggplot(data=df_best_optim, aes(x=epoch, y=valid_mae, color=run)) +
  geom_line() + 
  theme_bw() + 
  scale_y_continuous(limits=c(0, 0.15)) +
  scale_x_continuous(limits=c(0, 300)) +
  theme(plot.title = element_text(hjust = 0.5, size=16)) +
  ylab('validation-MAE') +
  theme(legend.position = "none") +
  labs(title='Validation error variablility')

ggsave(file.path(figures_dir, 'optimization_variablility_mae.pdf'), p, width = 20, height = 13, units = "cm")
p
```


```{r}
p <- ggplot(data=df_best_optim, aes(x=epoch, y=lr, color=run)) +
  geom_line() + 
  theme_bw() + 
  scale_x_continuous(limits=c(0, 300)) +
  ylab('learning-rate') +
  theme(plot.title = element_text(hjust = 0.5, size=16)) +
  theme(legend.position = "none") +
  labs(title='Learning rate schedule variability')

ggsave(file.path(figures_dir, 'optimization_variablility_lr.pdf'), p, width = 20, height = 13, units = "cm")
p
```


